[[plugins]]
package = "@netlify/plugin-sitemap"

# Uncomment the below when due to go live to public
# Some other things will need to be set up within Sentry.
# If you've not done this, then ask for help.
[[plugins]]
package = "@sentry/netlify-build-plugin"

[plugins.inputs]
  sentryOrg = "wmca-digital"
  sentryProject = "wmn-disruption-signup"

# Use staging for branch deploys for next-release
# So that dummy data from testing does not enter live DB
[context."next-release".environment]
  REACT_APP_API_HOST="https://rtccdisruptionsbfasldoiz.azurewebsites.net"
  REACT_APP_AUTOCOMPLETE_API="https://wmca-api-portal-staging.azure-api.net"
  REACT_APP_AUTOCOMPLETE_API_KEY="0d4cca4a2c5d40c3bfbbfe45d1bbf294"
  REACT_APP_ROADS_AUTOCOMPLETE_KEY="e0c1216f818a41be8d528ac1d4f7ebfd"

[context.deploy-preview.environment]
  REACT_APP_API_HOST="https://rtccdisruptionsbfasldoiz.azurewebsites.net"
  REACT_APP_AUTOCOMPLETE_API="https://wmca-api-portal-staging.azure-api.net"
  REACT_APP_AUTOCOMPLETE_API_KEY="0d4cca4a2c5d40c3bfbbfe45d1bbf294"
  REACT_APP_ROADS_AUTOCOMPLETE_KEY="e0c1216f818a41be8d528ac1d4f7ebfd"